/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simsql_runtime_Matrix */

#ifndef _Included_simsql_runtime_Matrix
#define _Included_simsql_runtime_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simsql_runtime_Matrix
 * Method:    getMatrixHeaderSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_Matrix_getMatrixHeaderSize
  (JNIEnv *, jclass);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    getNativeDoubleSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_Matrix_getNativeDoubleSize
  (JNIEnv *, jclass);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    initMatrix
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_initMatrix
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeReshape
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeReshape
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    allocatedMatrixSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_Matrix_allocatedMatrixSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    getMatrixSize1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_Matrix_getMatrixSize1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    getMatrixSize2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_Matrix_getMatrixSize2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeAddDouble
 * Signature: (JDDJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeAddDouble
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeAddVector
 * Signature: (JZD[DDJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeAddVector
  (JNIEnv *, jclass, jlong, jboolean, jdouble, jdoubleArray, jdouble, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeAddMatrix
 * Signature: (JZDJZDJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeAddMatrix
  (JNIEnv *, jclass, jlong, jboolean, jdouble, jlong, jboolean, jdouble, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeMultiplyDouble
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeMultiplyDouble
  (JNIEnv *, jclass, jlong, jdouble, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeMultiplyVector
 * Signature: ([DJZJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeMultiplyVector
  (JNIEnv *, jclass, jdoubleArray, jlong, jboolean, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeMultiplyMatrix
 * Signature: (JZJZJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeMultiplyMatrix
  (JNIEnv *, jclass, jlong, jboolean, jlong, jboolean, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeDivideMatrixDouble
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeDivideMatrixDouble
  (JNIEnv *, jclass, jlong, jdouble, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeDivideDoubleMatrix
 * Signature: (DJJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeDivideDoubleMatrix
  (JNIEnv *, jclass, jdouble, jlong, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeDivideVectorMatrix
 * Signature: (JZ[DJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeDivideVectorMatrix
  (JNIEnv *, jclass, jlong, jboolean, jdoubleArray, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeDivideMatrixVector
 * Signature: (JZ[DJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeDivideMatrixVector
  (JNIEnv *, jclass, jlong, jboolean, jdoubleArray, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeDivideMatrixMatrix
 * Signature: (JZJZJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_Matrix_nativeDivideMatrixMatrix
  (JNIEnv *, jclass, jlong, jboolean, jlong, jboolean, jlong);

/*
 * Class:     simsql_runtime_Matrix
 * Method:    nativeEqual
 * Signature: (JZJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_simsql_runtime_Matrix_nativeEqual
  (JNIEnv *, jclass, jlong, jboolean, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif