/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simsql_runtime_UDFunction */

#ifndef _Included_simsql_runtime_UDFunction
#define _Included_simsql_runtime_UDFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simsql_runtime_UDFunction
 * Method:    load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_UDFunction_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getLoadedName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simsql_runtime_UDFunction_getLoadedName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getLoadedOutputType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simsql_runtime_UDFunction_getLoadedOutputType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getLoadedInputTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_simsql_runtime_UDFunction_getLoadedInputTypes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    setBuffers
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/LongBuffer;)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_UDFunction_setBuffers
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getDoubleResult
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_simsql_runtime_UDFunction_getDoubleResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getIntResult
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_UDFunction_getIntResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getVectorResult
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_simsql_runtime_UDFunction_getVectorResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getMatrixResult
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_UDFunction_getMatrixResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_UDFunction
 * Method:    getStringResult
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simsql_runtime_UDFunction_getStringResult
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif