

/*****************************************************************************
 *                                                                           *
 *  Copyright 2014 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include "/usr/lib/jvm/java-7-oracle/include/jni.h"
/* Header for class simsql_runtime_VGFunction */

#ifndef _Included_simsql_runtime_VGFunction
#define _Included_simsql_runtime_VGFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simsql_runtime_VGFunction
 * Method:    load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_VGFunction_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    initializeSeed
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_initializeSeed
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    clearParams
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_clearParams
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    setBuffers
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/LongBuffer;Ljava/nio/LongBuffer;Ljava/nio/LongBuffer;)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_setBuffers
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    takeParams
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_takeParams
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    outputVals
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_simsql_runtime_VGFunction_outputVals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    finalizeTrial
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simsql_runtime_VGFunction_finalizeTrial
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getInputSchema
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_simsql_runtime_VGFunction_getInputSchema
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getOutputSchema
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_simsql_runtime_VGFunction_getOutputSchema
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getInputAttNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_simsql_runtime_VGFunction_getInputAttNames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getOutputAttNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_simsql_runtime_VGFunction_getOutputAttNames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getRandomOutputAtts
 * Signature: (J)[J
 */
//JNIEXPORT jlongArray JNICALL Java_simsql_runtime_VGFunction_getRandomOutputAtts
//  (JNIEnv *, jobject, jlong);

/*
 * Class:     simsql_runtime_VGFunction
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simsql_runtime_VGFunction_getName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
